apiVersion: apps/v1
kind: Deployment
metadata:
  name: villa-backend
  namespace: prod

spec:
  replicas: 2

  selector:
    matchLabels:
      app: villa-backend

  template:
    metadata:
      labels:
        app: villa-backend

      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "villa-prod-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/villa/prod"

    spec:
      serviceAccountName: villa-prod-sa

      containers:
      - name: villa-backend

        image: santosh2585/villa-backend:prod-1

        ports:
        - containerPort: 8086